name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install "django>=4.2,<5.0"
        pip install pandas numpy matplotlib seaborn plotly
        pip install "psycopg[binary]"
        pip install djongo
        pip install dnspython
        pip install flake8

    - name: Ejecutar análisis estático (flake8)
      run: flake8 .

    - name: Ejecutar migraciones
      run: |
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput

    - name: Ejecutar pruebas (si existen)
      run: |
        python manage.py test || echo "No hay pruebas, continuando..."
